server:
  port: 8082

myspcloud:
  item:
    url: http://127.0.0.1:8081/item/

# 起个名字作为服务名称(该服务注册到 eureka 注册中心的名称，比如订单服务)
spring:
  application:
    name: app-order
#  security:
#    # 配置用户的账号信息
#    user:
#      name: tudan
#      password: 123456

# 服务注册到 eureka 注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://tudan:123456@127.0.0.1:8100/eureka/,http://tudan:123456@127.0.0.1:9100/eureka/
    # 因为该应用为服务提供者，是 eureka 的一个客户端，需要注册到注册中心
    register-with-eureka: true
    # 是否需要从 eureka 上检索服务
    fetch-registry: true

app-commodity:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule